spring.application.name=apiGateway
server.port=9080

spring.cloud.gateway.server.webmvc.routes[0].id=authService
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://authService
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=complaintService
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://complaintService
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/complaints/**

spring.cloud.gateway.server.webmvc.routes[2].id=assignmentService
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://assignmentService
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/assignments/**

spring.cloud.gateway.server.webmvc.routes[3].id=notificationService
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://notificationService
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/notifications/**

eureka.client.serviceUrl.defaultZone=http://localhost:9000/eureka

jwt.secret=${JWT_SECRET}