spring.application.name=assignmentService
server.port=8083
spring.config.import=optional:file:../.env[.properties],optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5432/assignmentdb
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

eureka.client.serviceUrl.defaultZone=http://localhost:9000/eureka
eureka.instance.preferIpAddress=true

feign.circuitbreaker.enabled=true

resilience4j.circuitbreaker.instances.complaintService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.complaintService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.complaintService.waitDurationInOpenState=10s

resilience4j.circuitbreaker.instances.notificationService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.notificationService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.notificationService.waitDurationInOpenState=10s