spring.application.name=assignmentService
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/assignmentdb
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

eureka.client.serviceUrl.defaultZone=http://localhost:9000/eureka
eureka.instance.preferIpAddress=true